// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PorteroDigital.Infrastructure.Persistence;

#nullable disable

namespace PorteroDigital.Infrastructure.Migrations
{
    [DbContext(typeof(PorteroDigitalDbContext))]
    partial class PorteroDigitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("PorteroDigital.Domain.Entities.CameraConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId")
                        .IsUnique();

                    b.ToTable("CameraConfigurations", (string)null);
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("Houses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AddressLabel = "Pasillo Unidad 1",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 1",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-01"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AddressLabel = "Pasillo Unidad 2",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 2",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-02"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AddressLabel = "Pasillo Unidad 3",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 3",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-03"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AddressLabel = "Pasillo Unidad 4",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 4",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-04"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AddressLabel = "Pasillo Unidad 5",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 5",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-05"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AddressLabel = "Pasillo Unidad 6",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 6",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-06"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AddressLabel = "Pasillo Unidad 7",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 7",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-07"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AddressLabel = "Pasillo Unidad 8",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 8",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-08"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AddressLabel = "Pasillo Unidad 9",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 9",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-09"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AddressLabel = "Pasillo Unidad 10",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 10",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            AddressLabel = "Pasillo Unidad 11",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 11",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-11"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            AddressLabel = "Pasillo Unidad 12",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Identifier = "Casa 12",
                            IsActive = true,
                            QrToken = "TOKEN-CASA-12"
                        });
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId", "Email")
                        .IsUnique();

                    b.ToTable("Residents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa01@portero.local",
                            FullName = "Inquilino Casa 1",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAAAQ==.if5Ty0ZIb7uzTwuz43QMHdTGByrmZSlQuD1ZjISQaSg=",
                            PhoneNumber = "3410000001"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa02@portero.local",
                            FullName = "Inquilino Casa 2",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAAAg==.HoRkP04/2zC8kH+PBJf5jzVpzG8OdFFYQ6rYTEOGkJA=",
                            PhoneNumber = "3410000002"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa03@portero.local",
                            FullName = "Inquilino Casa 3",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAAAw==.xgAR/ZBqox9YEGa+NWkxkcGplfPAttlK3ouEXOdBIog=",
                            PhoneNumber = "3410000003"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa04@portero.local",
                            FullName = "Inquilino Casa 4",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAABA==.SU2Zziy244EHNoUH3QuduuS9Ux1fIwq5fxfirB5BoX8=",
                            PhoneNumber = "3410000004"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa05@portero.local",
                            FullName = "Inquilino Casa 5",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAABQ==.DtEZz6DxiIs3xIB9XUZxvs6mhejZNRKTmgeiC4A7DvE=",
                            PhoneNumber = "3410000005"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa06@portero.local",
                            FullName = "Inquilino Casa 6",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAABg==.9RBXsWBiqtiHn3bGzzvtGowMEX3nWl/bX8adfZbdml4=",
                            PhoneNumber = "3410000006"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa07@portero.local",
                            FullName = "Inquilino Casa 7",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAABw==.cPEfqFkG0nu0mZ+92yenG+Upti48XbgsRinAWsB35Qc=",
                            PhoneNumber = "3410000007"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa08@portero.local",
                            FullName = "Inquilino Casa 8",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAACA==.WUd5KIUtdXY7/RmzWvEIEmhRmfhDT7D2KrSCDDzqVeE=",
                            PhoneNumber = "3410000008"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa09@portero.local",
                            FullName = "Inquilino Casa 9",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAACQ==.nz13qjy7MdjuD0qJagl0gwwkVHICu+oL4CmLD2579tU=",
                            PhoneNumber = "3410000009"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa10@portero.local",
                            FullName = "Inquilino Casa 10",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAAEA==.HuuxfBRKW1NnRf7WQW/kgzI3+gkTEXROmX26KeX40lg=",
                            PhoneNumber = "3410000010"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa11@portero.local",
                            FullName = "Inquilino Casa 11",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000011"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAAEQ==.3CJUB3SwaQpTzOEnh07vX2haqBHvFApVhOLqF+OEitM=",
                            PhoneNumber = "3410000011"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "casa12@portero.local",
                            FullName = "Inquilino Casa 12",
                            HouseId = new Guid("00000000-0000-0000-0000-000000000012"),
                            IsActive = true,
                            IsPrimaryContact = true,
                            PasswordHash = "v1.AAAAEAAAAAAAAAAAAAAAEg==.59/X/RKEDVnXVS/tjcpt4DMAPCBsRGSvfw9t4gX4GpE=",
                            PhoneNumber = "3410000012"
                        });
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.ResidentDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationSound")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId", "PushToken")
                        .IsUnique();

                    b.ToTable("ResidentDevices", (string)null);
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.VisitorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentDecision")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId", "RequestedAtUtc");

                    b.ToTable("VisitorLogs", (string)null);
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.CameraConfiguration", b =>
                {
                    b.HasOne("PorteroDigital.Domain.Entities.House", "House")
                        .WithOne("CameraConfiguration")
                        .HasForeignKey("PorteroDigital.Domain.Entities.CameraConfiguration", "HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.Resident", b =>
                {
                    b.HasOne("PorteroDigital.Domain.Entities.House", "House")
                        .WithMany("Residents")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.ResidentDevice", b =>
                {
                    b.HasOne("PorteroDigital.Domain.Entities.Resident", "Resident")
                        .WithMany("Devices")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.VisitorLog", b =>
                {
                    b.HasOne("PorteroDigital.Domain.Entities.House", "House")
                        .WithMany("VisitorLogs")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.House", b =>
                {
                    b.Navigation("CameraConfiguration");

                    b.Navigation("Residents");

                    b.Navigation("VisitorLogs");
                });

            modelBuilder.Entity("PorteroDigital.Domain.Entities.Resident", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
